server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://hn7001.com:7001/eureka/,http://hn7002.com:7002/eureka/,http://hn7003.com:7003/eureka/
